import{a as S,S as q,i}from"./assets/vendor-BOD_307a.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function f(o,t=1){return(await S.get("https://pixabay.com/api/",{params:{key:"55193663-01ca752f3a3efdba5a4e579f6",q:o,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const g=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more-btn"),M=new q(".gallery a",{captionsData:"alt",captionDelay:250});function p(o){const t=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:c,comments:w,downloads:v})=>`
            <li class="gallery-item">
                <a class="gallery-link" href="${a}">
                    <img class="gallery-image" src="${s}" alt="${e}" />
                </a>
                <div class="info">
                    <p class="info-item"><b>Likes</b> ${r}</p>
                    <p class="info-item"><b>Views</b> ${c}</p>
                    <p class="info-item"><b>Comments</b> ${w}</p>
                    <p class="info-item"><b>Downloads</b> ${v}</p>
                </div>
            </li>`).join("");g.insertAdjacentHTML("beforeend",t),M.refresh()}function P(){g.innerHTML=""}function b(){y.classList.add("is-visible")}function u(){y.classList.remove("is-visible")}function L(){h.classList.remove("is-hidden")}function m(){h.classList.add("is-hidden")}let l="",n=1,d=0;const $=document.querySelector(".form");$.addEventListener("submit",async o=>{if(o.preventDefault(),l=o.target.elements["search-text"].value.trim(),!l){i.warning({message:"Please enter a search query!"});return}n=1,P(),m(),b();try{const t=await f(l,n);if(u(),d=t.totalHits,t.hits.length===0){i.error({message:"Sorry, no images found!"});return}p(t.hits);const s=Math.ceil(d/15);d>0&&n>=s?(m(),i.info({message:"We're sorry, but you've reached the end of search results."})):L()}catch{u(),i.error({message:"Something went wrong!"})}o.target.reset()});const x=document.querySelector(".load-more-btn");x.addEventListener("click",async()=>{n+=1,m(),b();try{const o=await f(l,n);u(),p(o.hits);const t=document.querySelector(".gallery-item");if(t){const a=t.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}const s=Math.ceil(d/15);n>=s?(m(),i.info({message:"We're sorry, but you've reached the end of search results."})):L()}catch{u(),i.error({message:"Error loading more images!"})}});
//# sourceMappingURL=index.js.map
