import{a as S,S as q,i as n}from"./assets/vendor-BOD_307a.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();async function f(o,t=1){return(await S.get("https://pixabay.com/api/",{params:{key:"55193663-01ca752f3a3efdba5a4e579f6",q:o,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const g=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more-btn"),M=new q(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const t=o.map(({webformatURL:a,largeImageURL:s,tags:e,likes:r,views:i,comments:w,downloads:v})=>`
            <li class="gallery-item">
                <a class="gallery-link" href="${s}">
                    <img class="gallery-image" src="${a}" alt="${e}" />
                </a>
                <div class="info">
                    <p class="info-item"><b>Likes</b> ${r}</p>
                    <p class="info-item"><b>Views</b> ${i}</p>
                    <p class="info-item"><b>Comments</b> ${w}</p>
                    <p class="info-item"><b>Downloads</b> ${v}</p>
                </div>
            </li>`).join("");g.insertAdjacentHTML("beforeend",t),M.refresh()}function P(){g.innerHTML=""}function b(){p.classList.add("is-visible")}function d(){p.classList.remove("is-visible")}function L(){y.classList.remove("is-hidden")}function u(){y.classList.add("is-hidden")}let l="",c=1,m=0;const $=document.querySelector(".form");$.addEventListener("submit",async o=>{if(o.preventDefault(),l=o.target.elements["search-text"].value.trim(),!l){n.warning({message:"Please enter a search query!"});return}c=1,P(),u(),b();try{const t=await f(l,c);if(d(),m=t.totalHits,t.hits.length===0){n.error({message:"Sorry, no images found!"});return}h(t.hits),m>15&&L()}catch{d(),n.error({message:"Something went wrong!"})}o.target.reset()});const B=document.querySelector(".load-more-btn");B.addEventListener("click",async()=>{c+=1,u(),b();try{const o=await f(l,c);d(),h(o.hits);const t=document.querySelector(".gallery-item");if(t){const s=t.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}const a=Math.ceil(m/15);c>=a?(u(),n.info({message:"We're sorry, but you've reached the end of search results."})):L()}catch{d(),n.error({message:"Error loading more images!"})}});
//# sourceMappingURL=index.js.map
